"use client";

import { usePathname } from "next/navigation";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/ui/Footer";
import { ThemeProvider } from "./provider/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Qwik Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const noHeader =
    pathname.includes("sign-in") ||
    pathname.includes("sign-up") ||
    pathname.includes("qwik-chat");

  const noFooter = pathname.includes("qwik-chat");

  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen max-w-[1920px] min-w-fit mx-auto px4 relative bg-[#f0f2f5] text-gray pb20 overflow-x-hidden `}
      >
        <ThemeProvider>
          <Toaster richColors position="top-right" />
          {!noHeader && <Navbar />}
          {children}
          {!noFooter && <Footer />}
        </ThemeProvider>
      </body>
    </html>
  );
}
